/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package domitory;

import domitory.views.BookingViews;
import java.awt.CardLayout;
import java.awt.Container;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import domitory.views.RoomView;
import domitory.views.TenantViews;
import java.awt.Color;

/**
 *
 * @author Na Standa
 */
public class Home2 extends javax.swing.JFrame {

    /**
     * Creates new form Home2
     */
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DomitoryPU");
    
    public Home2() {
        initComponents();
    }

    public BookingViews getBookingViews1() {
        return bookingViews1;
    }

    public RoomView getRoomView1() {
        return roomView1;
    }

    public TenantViews getTenantViews1() {
        return tenantViews1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeView1 = new domitory.views.HomeView();
        roomView1 = this.roomView1 = new RoomView(this,emf);
        bookingViews1 = this.bookingViews1=new domitory.views.BookingViews(this,emf);
        tenantViews1 = this.tenantViews1=new domitory.views.TenantViews(this,emf);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout homeView1Layout = new javax.swing.GroupLayout(homeView1);
        homeView1.setLayout(homeView1Layout);
        homeView1Layout.setHorizontalGroup(
            homeView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        homeView1Layout.setVerticalGroup(
            homeView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        getContentPane().add(homeView1, "cardHomeView");
        getContentPane().add(roomView1, "cardRoomView");
        getContentPane().add(bookingViews1, "cardBookingViews");
        getContentPane().add(tenantViews1, "cardTenantViews");

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu1.setText("Home");

        jMenuItem2.setText("Home");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu2.setText("Book/Rent and Remove");

        jMenuItem4.setText("Book/Rent and Remove");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu3.setText("Pay");

        jMenuItem1.setText("Pay");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu4.setText("Room");

        jMenuItem5.setText("RoomList");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Container tn=this.getContentPane();
        CardLayout layout=(CardLayout) tn.getLayout();
        layout.show(tn, "cardTenantViews");
        jMenu1.setForeground(Color.black);
        jMenu2.setForeground(Color.black);
        jMenu3.setForeground(Color.red);
        jMenu4.setForeground(Color.black);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Container h=this.getContentPane();
        CardLayout layout=(CardLayout) h.getLayout();
        layout.show(h, "cardHomeView");
        jMenu1.setForeground(Color.red);
        jMenu2.setForeground(Color.black);
        jMenu3.setForeground(Color.black);
        jMenu4.setForeground(Color.black);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Container bo=this.getContentPane();
        CardLayout layout=(CardLayout) bo.getLayout();
        layout.show(bo, "cardBookingViews");
        jMenu1.setForeground(Color.black);
        jMenu2.setForeground(Color.red);
        jMenu3.setForeground(Color.black);
        jMenu4.setForeground(Color.black);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Container ro=this.getContentPane();
        CardLayout layout=(CardLayout) ro.getLayout();
        layout.show(ro, "cardRoomView");
        jMenu1.setForeground(Color.black);
        jMenu2.setForeground(Color.black);
        jMenu3.setForeground(Color.black);
        jMenu4.setForeground(Color.red);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private domitory.views.BookingViews bookingViews1;
    private domitory.views.HomeView homeView1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private domitory.views.RoomView roomView1;
    private domitory.views.TenantViews tenantViews1;
    // End of variables declaration//GEN-END:variables

    

}
