/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package domitory;

import java.awt.CardLayout;
import java.awt.Container;

/**
 *
 * @author Na Standa
 */
public class Home2 extends javax.swing.JFrame {

    /**
     * Creates new form Home2
     */
    public Home2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tenantViews1 = new domitory.views.TenantViews();
        tenantViews2 = new domitory.views.TenantViews();
        otherView1 = new domitory.views.OtherView();
        tenantViews3 = new domitory.views.TenantViews();
        otherView2 = new domitory.views.OtherView();
        homeView2 = new domitory.views.HomeView();
        homeView1 = new domitory.views.HomeView();
        tenantViews4 = new domitory.views.TenantViews();
        otherView3 = new domitory.views.OtherView();
        homeView3 = new domitory.views.HomeView();
        bookingViews1 = new domitory.views.BookingViews();
        bookingViews2 = new domitory.views.BookingViews();
        bookingViews3 = new domitory.views.BookingViews();
        homeView5 = new domitory.views.HomeView();
        tenantViews5 = new domitory.views.TenantViews();
        otherView4 = new domitory.views.OtherView();
        roomView1 = new domitory.views.RoomView();
        bookingViews5 = new domitory.views.BookingViews();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout homeView2Layout = new javax.swing.GroupLayout(homeView2);
        homeView2.setLayout(homeView2Layout);
        homeView2Layout.setHorizontalGroup(
            homeView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        homeView2Layout.setVerticalGroup(
            homeView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        homeView1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout homeView3Layout = new javax.swing.GroupLayout(homeView3);
        homeView3.setLayout(homeView3Layout);
        homeView3Layout.setHorizontalGroup(
            homeView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        homeView3Layout.setVerticalGroup(
            homeView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout homeView5Layout = new javax.swing.GroupLayout(homeView5);
        homeView5.setLayout(homeView5Layout);
        homeView5Layout.setHorizontalGroup(
            homeView5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        homeView5Layout.setVerticalGroup(
            homeView5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        getContentPane().add(homeView5, "cardhome");
        getContentPane().add(tenantViews5, "cardt");
        getContentPane().add(otherView4, "cardo");
        getContentPane().add(roomView1, "cardr");
        getContentPane().add(bookingViews5, "cardb");

        jMenu1.setText("File");

        jMenuItem2.setText("Home");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Book");

        jMenuItem4.setText("Book");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tenant");

        jMenuItem1.setText("TenantList");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Room");

        jMenuItem5.setText("RoomList");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Other");

        jMenuItem3.setText("Other");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Container tn=this.getContentPane();
        CardLayout layout=(CardLayout) tn.getLayout();
        layout.show(tn, "cardt");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Container h=this.getContentPane();
        CardLayout layout=(CardLayout) h.getLayout();
        layout.show(h, "cardhome");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Container ot=this.getContentPane();
        CardLayout layout=(CardLayout) ot.getLayout();
        layout.show(ot, "cardo");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Container bo=this.getContentPane();
        CardLayout layout=(CardLayout) bo.getLayout();
        layout.show(bo, "cardb");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Container ro=this.getContentPane();
        CardLayout layout=(CardLayout) ro.getLayout();
        layout.show(ro, "cardr");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private domitory.views.BookingViews bookingViews1;
    private domitory.views.BookingViews bookingViews2;
    private domitory.views.BookingViews bookingViews3;
    private domitory.views.BookingViews bookingViews5;
    private domitory.views.HomeView homeView1;
    private domitory.views.HomeView homeView2;
    private domitory.views.HomeView homeView3;
    private domitory.views.HomeView homeView5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private domitory.views.OtherView otherView1;
    private domitory.views.OtherView otherView2;
    private domitory.views.OtherView otherView3;
    private domitory.views.OtherView otherView4;
    private domitory.views.RoomView roomView1;
    private domitory.views.TenantViews tenantViews1;
    private domitory.views.TenantViews tenantViews2;
    private domitory.views.TenantViews tenantViews3;
    private domitory.views.TenantViews tenantViews4;
    private domitory.views.TenantViews tenantViews5;
    // End of variables declaration//GEN-END:variables
}
